import type { ApplicationSettings } from "@/lib/app-settings";
import type { EffectiveCapabilities, FeatureKey } from "@/lib/features";
import type { AppRole, BusinessPlan, StaffAccessScope } from "@/lib/types";
import type { BranchProfile, StationProfile } from "@/lib/types";

export type AppShellPayload = {
  role: AppRole | null;
  hasUser: boolean;
  usingDemoData: boolean;
  sessionUserId: string | null;
  sessionBusinessId: string | null;
  sessionBranchId: string | null;
  activeBusinessSlug: string;
  businesses: Array<{ slug: string; name: string }>;
  activeBranchId: string;
  activeBranchProfile: BranchProfile;
  activeStationProfile: StationProfile;
  hasMixedBranchProfiles: boolean;
  forcedBranchSelectionFromAll: boolean;
  branches: Array<{ id: string; name: string; branch_profile: BranchProfile }>;
  currentPlan: BusinessPlan;
  branchAccessScope: StaffAccessScope;
  canSwitchBranches: boolean;
  effectiveCapabilities: EffectiveCapabilities;
  featureOverrides: Partial<Record<FeatureKey, boolean>>;
  brandName: string;
  logoUrl?: string;
  sidebarTheme: ApplicationSettings["sidebarTheme"];
  sidebarAccentColor: ApplicationSettings["sidebarAccentColor"];
  ownerSidebarOrder: ApplicationSettings["ownerSidebarOrder"];
  adminSidebarOrder: ApplicationSettings["adminSidebarOrder"];
  mobileAppExperienceEnabled: boolean;
  mobileReadOnlyPwaEnabled: boolean;
};
