export const POS_CLIENT_QUEUE_TABLES_ENABLED = process.env.NEXT_PUBLIC_POS_CLIENT_QUEUE_TABLES === "true";
export const POS_CLIENT_QUEUE_CASHIER_ENABLED = process.env.NEXT_PUBLIC_POS_CLIENT_QUEUE_CASHIER === "true";
